[package]
name = "rawweave-raw-nodes"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rawweave-color.workspace = true
rawweave-image.workspace = true
rawweave-node-api.workspace = true
rawweave-raw.workspace = true
rawweave-rendering.workspace = true

[dev-dependencies]
rawweave-graph.workspace = true
rawweave-project.workspace = true
serde_json.workspace = true
