[package]
name = "rawweave-project"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rawweave-core.workspace = true
rawweave-core-image.workspace = true
rawweave-core-values.workspace = true
rawweave-graph.workspace = true
rawweave-image.workspace = true
rawweave-node-api.workspace = true
thiserror.workspace = true
