[package]
name = "rawweave-graph"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytemuck.workspace = true
rawweave-color.workspace = true
rawweave-core.workspace = true
rawweave-image.workspace = true
rawweave-node-api.workspace = true
rawweave-raw.workspace = true
rawweave-rendering.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
rawweave-core-image.workspace = true
rawweave-core-values.workspace = true
rawweave-image.workspace = true
